# Generated by Django 2.0.6 on 2018-06-24 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFilmeFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'filme favorito do usuário',
                'verbose_name_plural': 'usuários - filmes favoritos',
                'permissions': (('view_usuario_filme_favorito', 'Can view filmes favoritos de usuários'),),
            },
        ),
    ]
