# Generated by Django 2.0.6 on 2018-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuariofilmefavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dados_publicos_api',
            field=models.BooleanField(default=False, verbose_name='Disponibiliza dados do usuário via api pública.'),
        ),
    ]
