# Generated by Django 2.0.6 on 2018-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_dados_publicos_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofilmefavorito',
            name='titulo',
            field=models.CharField(default='', max_length=255, verbose_name='Título do Filme'),
            preserve_default=False,
        ),
    ]
