# Generated by Django 2.0.6 on 2018-06-25 03:02

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuariofilmefavorito_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino')], null=True),
        ),
    ]
