# Generated by Django 2.0.6 on 2018-06-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180625_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofilmefavorito',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Filme'),
        ),
    ]
